- name: "Create wordpress container"
  docker_container: 
    name: "{{ wp.container_name }}"
    image: "{{ wp.docker_image }}"
    volumes:
    - "/var/www/{{ username }}:/var/www/html:rw"
    restart: true
    ports: 
    - "80:80"
    env: 
      WORDPRESS_DB_HOST: "{{ ansible_ssh_host }}"
      WORDPRESS_DB_USER: "{{ mysql.user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql.user_password }}"
      WORDPRESS_DB_NAME: "{{ mysql.db_name }}"
      WORDPRESS_DEBUG: "true"
    container_default_behavior: "compatibility"

- name: WP container test
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 5
    msg: "wordpress container feel bad :=("